apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: kube-prometheus-stack
    targetRevision: 82.4.3
    helm:
      values: |
        grafana:
          adminPassword: "your-safe-password"
          sidecar:
            dashboards:
              enabled: true
              label: grafana_dashboard
              searchNamespace: ALL
          # Robustness Fix: Ensuring Grafana doesn't OOM during the Sock Shop load
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 256Mi

        prometheus:
          prometheusSpec:
            # Resource Fix: Giving Prometheus enough room to handle 14 microservices
            resources:
              requests:
                memory: 1Gi
              limits:
                memory: 4Gi 
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: local-path
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 5Gi
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
